development:
  bucket: purex_live
  access_key_id: AKIAISN5QHJWVJB3AM6Q
  secret_access_key: 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

production:
  bucket: purex_live
  access_key_id: AKIAISN5QHJWVJB3AM6Q
  secret_access_key: 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

staging:
  bucket: purex-staging
  access_key_id: AKIAISN5QHJWVJB3AM6Q
  secret_access_key: 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

test:
  bucket: purex-test
  access_key_id: AKIAISN5QHJWVJB3AM6Q
  secret_access_key: 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

sandbox:
  bucket: purex-sandbox
  access_key_id: AKIAISN5QHJWVJB3AM6Q
  secret_access_key: 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
