development:
  bucket: purex_live
  access_key_id: AKIAINCGR2Z7K3VYJO4A
  secret_access_key: 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
  
production:
  bucket: purex_live
  access_key_id: AKIAINCGR2Z7K3VYJO4A
  secret_access_key: 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

staging:
  bucket: purex_staging
  access_key_id: AKIAINCGR2Z7K3VYJO4A
  secret_access_key: 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

test:
  bucket: purex-test
  access_key_id: AKIAINCGR2Z7K3VYJO4A
  secret_access_key: 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

